### ISSUE TITLE
小米10t 海外版能不能用啊？

### ISSUE THREAD

**Issue by roadshow1997** [rewqazxv/magisk-mipay-lmi#1]
小米10t 海外版能不能用这个方法添加小米钱包呢？

**Comment by rewqazxv** [comment]
据说提取出来的文件不通用，但是方法是一样的。我可以试着提取一份

**Comment by rewqazxv** [comment]
可能不行，看起来不同机型的代码不一样
我提取了一份小米10的，你可以都试试
https://github.com/rewqazxv/magisk-mipay-lmi/releases/tag/umi
