### ISSUE TITLE
Failed to use this patch with PixelExperencePlus

### ISSUE THREAD

**Issue by YucongDing** [rewqazxv/magisk-mipay-lmi#2]
MiWallet failed to start in PE+

**Comment by rewqazxv** [comment]
有几个可能：

1. 小米智能卡要求始终允许获取位置才能用，不然点不开公交卡
2. 以前需要开启小米找回手机
3. 这个项目主要是给xiaomi.eu rom用的，可能依赖小米服务框架（小米账号, 小米云服务, etc.)

建议尝试给权限，安装小米服务，或者用微信nfc交联公交卡

**Comment by YucongDing** [comment]
已经尝试给了权限，仍然启动失败，可能需要小米服务的支持。另外请问您说的微信nfc公交卡具体名字是？

**Comment by rewqazxv** [comment]
搜索小程序 乘车卡

**Comment by YucongDing** [comment]
好的已经用上感谢

**Comment by rewqazxv** [comment]
ok
